### ISSUE TITLE
External tools integration

### ISSUE THREAD

**Issue by mikekazakov** [mikekazakov/nc#13]
I think if you've added an easy way to support third party apps it would give Files a huge extra power without much work on your part. I'm thinking about something simple: you pick an app (or just a binary) and then it can get arguments based on what's going on in Files' windows. Examples of arguments you could pass (one of more):

folder path in the left/right window
file name in the left/right window
full file path in l/r window
user entered value
list of selected files
etc
This way, I could easily add tools for quick folder sync or file diff (using i.e. Beyond Compare) that I'm missing from Total Commander. I.e. something to batch rename files, thing like "Open new terminal here" (I love your terminal integration, but sometimes I just want to open a standalone window), "Create and edit new file here", etc.

Adding keyboard shortcuts for such extra tools would be a critical feature, to make them powerful.

**Comment by darekrusin** [comment]
What a great idea! :) :+1:
