### ISSUE TITLE
Dynamic column width mode ("Brief" mode)

### ISSUE THREAD

**Issue by darekrusin** [mikekazakov/nc#35]
Discussion started here: http://magnumbytes.com/forum/viewtopic.php?f=6&t=71

But in short: make the column width match the longest name in current directory. Here's how Commander One does it, which is pretty much the same as in Total Commander:

![image](https://cloud.githubusercontent.com/assets/8372873/17168333/2cfe24ec-53e2-11e6-95e8-697ce8f4f0de.png)

![image](https://cloud.githubusercontent.com/assets/8372873/17168337/344d11e0-53e2-11e6-9f77-ead36bf66ba6.png)

**Comment by mikekazakov** [comment]
Done in 1.2.0
