### ISSUE TITLE
Find in files - workflow and keyboard navigation improvements

### ISSUE THREAD

**Issue by darekrusin** [mikekazakov/nc#36]
I'm in a folder with some source code. Let's assume I want to look up `BX_PLATFORM_OSX` and how it's used in files.

* ALT+F7 - opens search window
* [x] note that the search doesn't need asterisk, if I type "on" and press ENTER it will find everything which includes the text; which is what I want almost every time, adding asterisks is annoying

![image](https://cloud.githubusercontent.com/assets/8372873/17169684/fee16bee-53e8-11e6-85cc-fe48589defb1.png)

* ok, back to the beginning... ALT+F7 to open the window, ALT+T to focus on the find text field, type `BX_PLATFORM_OSX` and press ENTER
* note that *Go to file* button is highlighted by default... which means I'm in a different mode. Clever, since now that I've searched I usually want to check the results.
* [x] I hit DOWN ARROW and I'm in the search result box. I can keep hitting ARROWS button to select the file I want

![image](https://cloud.githubusercontent.com/assets/8372873/17169870/e09efbe6-53e9-11e6-90b5-28b1addcafc5.png)

* [x] Now I can press F3 and it will open the preview of the file in a **separate** window.
* [x] But here's the coolest thing, when I hit F3 in that preview window again (F3 in that case is seach again, that would be CMD+G on Mac) the preview window remembers what I've searched for in files and searches for the same thing in previewed text. Amazing and so convenient!

![image](https://cloud.githubusercontent.com/assets/8372873/17169942/385b2800-53ea-11e6-81a0-798645516445.png)

* I can keep opening as many preview windows as I want, quickly checking how the phrase is used across them
* [x] When I'm moving through the search result list with arrow keys I can press ENTER anytime and the search window will close and I'll be taken to that specific file in the file panel. Without touching the mouse! :)

So that's the basic workflow. It's very smooth and convenient. I've marked things I'd **love** to see in Nimble Commander with checkboxes.

**Comment by mikekazakov** [comment]
Seems to be done.

**Comment by JunfengJia** [comment]
It will be helpful if user can select searching option by keyboard.
