### ISSUE TITLE
Crash with samba shares 

### ISSUE THREAD

**Issue by hugo187** [mikekazakov/nc#60]
I am experiencing crashes when working with SMB shares. I am able to reproduce the crashes when  mounted from another macOS machine and also when mounted from Debian machine.

1. It crashes when Eject Volume (Cmd + E) command is executed. It doesn't crash though if I unmount the share via Finder.

2. It also crashes when I try to copy/move a file without proper read permissions (e.g., owner is a different user and the file is not group/world readable).

Crash reports attached.

[no_permissions_crash.log.txt](https://github.com/mikekazakov/nc/files/771895/no_permissions_crash.log.txt)
[share_eject_crash.log.txt](https://github.com/mikekazakov/nc/files/771896/share_eject_crash.log.txt)

**Comment by mikekazakov** [comment]
share_eject_crash.log.txt is fixed in b2042: http://magnumbytes.com/forum/viewtopic.php?f=7&t=216

**Comment by mikekazakov** [comment]
no_permissions_crash.log.txt - confirm, fixed.
