### ISSUE TITLE
Terminal font - weird spacing after upgrade to 1.2

### ISSUE THREAD

**Issue by darekrusin** [mikekazakov/nc#62]
The full screen terminal looks... weird after upgrade.

![image](https://cloud.githubusercontent.com/assets/8372873/23585294/1f144978-017b-11e7-98cf-80155da44a63.png)

I don't see anything strange in font settings though:

![image](https://cloud.githubusercontent.com/assets/8372873/23585303/756df59e-017b-11e7-8023-3a1dfafd340a.png)

**Comment by mikekazakov** [comment]
It's a fallback value for sure, right one is monospaced, like Menlo-Regular. 
This must be connected with previous issue with partially invalid config state.

**Comment by darekrusin** [comment]
Hmm... Any tips on how to fix this (or debug the issue)?

**Comment by mikekazakov** [comment]
Does it stays after reselecting current theme? I though it should have reverted to normal state.
Regardless, this of course can be fixed by just selecting the right font via "Custom" button.

**Comment by darekrusin** [comment]
Reselecting the theme doesn't help. Neither restarting. But changing to `Menlo, 11` by hand, using the Custom button did the trick. Thanks.

**Comment by darekrusin** [comment]
I believe it's might have been something on my side, maybe some config error carried over from older dev preview builds. It's safe to close this.
