### ISSUE TITLE
Brief mode columns don't have full height after restart

### ISSUE THREAD

**Issue by darekrusin** [mikekazakov/nc#63]
I have this:

![image](https://cloud.githubusercontent.com/assets/8372873/23599767/430c6cac-0243-11e7-9b79-fa7cc1754d2c.png)

Now I close the app (CMD+Q), start it again and I see this:

![image](https://cloud.githubusercontent.com/assets/8372873/23599777/53646dca-0243-11e7-9c89-d50dbfe32cad.png)

After going up and down in directories it all refreshes back to the proper state. These are my settings:

![image](https://cloud.githubusercontent.com/assets/8372873/23599791/614aac24-0243-11e7-9a0c-96ca929084bd.png)

**Comment by mikekazakov** [comment]
Darek, I wasn't able to reproduce it. Any additional hints might help.

**Comment by darekrusin** [comment]
Let me know what can I do, Mike? I just tried messing around with resetting the settings (didn't help) then I removed the whole NC folder from Application Support (didn't help). I lost patience, went nuclear and used App Cleaner to remove every trace of NC from the system, then reinstalled it fresh... didn't help. Same thing happens.

**Comment by darekrusin** [comment]
I've just rebooted the machine, to be sure. Didn't help either.

* It's not in brief mode only, default short and medium modes have the same problem
* Worst thing: every new tab I open starts with this limited 5 lines high view

I'm on El Capitan 10.11.6.

**Comment by mikekazakov** [comment]
Oh, 10.11 is at least something.
BTW, is overlapped terminal activated?
And does list view work correctly meanwhile?

**Comment by darekrusin** [comment]
Man, I've spent way too much time on this already ;) I've upgraded NC on my other machine, Mac Mini and behold -- it was working well there. WTF, methinks?

Then I thought -- maybe it's because of retina vs non-retina? So I tried hooking my MacBook, which was causing the trouble, to external screen. And voila... it started working well. But then I unhooked the screen, went back to retina and... it's still good. OMG, did it autocorrect itself? What the hell... :) And then I experimented some more and now I know what's the root cause....

*...drumroll please...*

Freaking **trackpad vs mouse** issue. On my MacBook, when I'm on trackpad only -- it's breaking. When I'm on mouse, it's all good. Disconnect mouse -- all broken again.

I imagine it would be the same for other people as well? In any case, I think this nails down the issue so it should be easy to repro on your side now.

**Comment by mikekazakov** [comment]
Dammit, it's a really tough stars alignment.
Looks like it happens only on 10.11, as both my MacBookPro and my MacMini with external trackpad runs fine on 10.12. And 10.11 working in VM treats trackpad as a mouse so this issue does not appear there.
Ok, I'll try to add some fix for 10.11 ASAP.
Thanks for your investigation!

**Comment by darekrusin** [comment]
I'll probably be upgrading to 10.12 sometimes next week, so we'll see what happens then.

But one thing just came to my mind: did you rule out scrollbar settings? Like always visible, based on input device, etc? Maybe it's something in that area...

**Comment by darekrusin** [comment]
Yeah, I had a moment to check and just as I thought:

* No bug at this settings:

![image](https://cloud.githubusercontent.com/assets/8372873/23765990/749b48fc-0503-11e7-8106-f8c697fdd0c2.png)

* But this setting triggers the issue:

![image](https://cloud.githubusercontent.com/assets/8372873/23766024/93e377ca-0503-11e7-9402-af8becb3f552.png)

So if you have it set to "Always" try changing and see if you can repro.

**Comment by mikekazakov** [comment]
Wow, that's absolutely fascinating.
In my case (10.11.6 in Parallels VM), this issue appeared when scrolling setting was set to "When scrolling". For some reason, with this combination of stars position, weather condition and phase of the moon, NSScrollView decides that during the initial layout it will automatically resize it's background view, but not the actual content view.
I've added some flags to enforce the resizing and looks like the issue is gone, at least in my testing environment. Could you please check it on your side?
http://magnumbytes.com/downloads/previews/nimble-commander-1.2.0(2085).zip
If everything is ok - I'll push this fix into the auto-update system.

**Comment by darekrusin** [comment]
The new version works well. You fixed it 👍
