### ISSUE TITLE
Text search ignored when using case sensitive and whole phrase

### ISSUE THREAD

**Issue by darekrusin** [mikekazakov/nc#64]
Here's what I'm trying to do:

![image](https://cloud.githubusercontent.com/assets/8372873/23944283/8cf389c8-0972-11e7-85fb-0c06869c4665.png)

But when I do that, the text gets cleared out and I get basically all the files within the wildcards. There text search is ignored.

![image](https://cloud.githubusercontent.com/assets/8372873/23944315/b235291c-0972-11e7-9b52-9a333650e73a.png)

When I disable case sensitive and whole phrase is seems to work better. I'm on Version 1.2.0 (2085).

**Comment by mikekazakov** [comment]
Dark, I've tried to reproduce it. You've clicked the "Search" button with a mouse after typing the query, right?

**Comment by darekrusin** [comment]
I might have used the keyboard (always prefer the keyboard), but I just checked clicking the mouse and it breaks this way as well. So yeah, clicking with the mouse.

Here's a use case.

* Two files, like this:

![image](https://cloud.githubusercontent.com/assets/8372873/24041572/6bc6ecb6-0b0e-11e7-843b-7f4060a2d91d.png)

* Quit NC, start it again... just to be sure.
* CMD+F to start search
* And here's what I'm getting:

![nc-search-bug](https://cloud.githubusercontent.com/assets/8372873/24041711/e7951af2-0b0e-11e7-85c3-725092fbcb41.gif)

* Bonus case: sometimes the text goes back to previous value, like this:

![nc-search-bug2](https://cloud.githubusercontent.com/assets/8372873/24041836/7a2463be-0b0f-11e7-9bcf-ddb3a985605b.gif)

(Please excuse these poor quality gifs... the tool I'm using, Annotate, doesn't seem to be handling this well)

**Comment by mikekazakov** [comment]
Fixed in b2161.
